### PR TITLE
Add .gitignore file

### PR DESCRIPTION
**Pull request by ksami**
Added .gitignore to ignore temporary files created by coqide to prevent unnecessary confusion and commits

### CODE REVIEW

**Comment by jeehoonkang** [comment]
Thank you for your contribution.

But why your `.gitignore` contains `sf/*.v#`? I think `*.v#` would be sufficient to ignore `sf/*.v#`.

Jeehoon

**Comment by ksami** [comment]
Oh yes it can, sorry I'll push another commit

**Comment by jeehoonkang** [comment]
I would like to close this pull request, since I modified `.gitignore`: ebbd2bed7d470784903a366d0421931cb3c87a8b

This is because I already maintained a `.gitignore` in `sf` directory, and I would like not to create another one.

Sorry!

**Comment by ksami** [comment]
Oh I did not notice that one. Yes okay

**Pull request closed without merging**
